# SPRING CONFIGS
spring:
  application:
    name: crud-spring-boot
# DATABASE CONFIGS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# DOCUMENTATION CONFIGS
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
# OTHER CONFIGS
server:
  port: 8080