# SPRING CONFIGS
spring:
  application:
    name: crud-spring-boot
    description: Aplicação para gerenciar o cadastro de produtos.
# DATABASE CONFIGS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
# DOCUMENTATION CONFIGS
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs